# 第七次实践

## 第一题

```{r}
# 自定义绘图函数
myplot <- function(xdata, ydata, title = "", xlm, ylb, col = "black", ylm = c(0, 1)) {
    plot(xdata, ydata,
        type = "l", col = col,
        main = paste(title, ylb), xlab = "X", ylab = ylb,
        xlim = xlm, ylim = ylm
    )
}
# 设置每次能输出 2*2 的图像个数，按行顺序排列
par(mfrow = c(2, 2))
ylb <- c("概率密度", "概率分布") # 定义绘图时 # 定义绘图时 # 定义绘图时的 Y 轴名称

# 均匀分布
xlm <- c(-2, 2) # 绘图时 X 轴范围
xrg <- seq(-2, 2, 0.01) # 绘图时变量 X 的取值
# 绘制不同均匀分布的概率密度函数图像
myplot(xrg, dunif(xrg, 0, 1), "X~U(0,1)", xlm, ylb[1])
myplot(xrg, dunif(xrg, 0, 2), "X~U(0,2)", xlm, ylb[1])
myplot(xrg, dunif(xrg, -1, 1), "X~U(-1,1)", xlm, ylb[1])
myplot(xrg, dunif(xrg, -2, 2), "X~U(-2,2)", xlm, ylb[1])
# 绘制不同均匀分布的概率分布函数图像
myplot(xrg, punif(xrg, 0, 1), "X~U(0,1)", xlm, ylb[2])
myplot(xrg, punif(xrg, 0, 2), "X~U(0,2)", xlm, ylb[2])
myplot(xrg, punif(xrg, -1, 1), "X~U(-1,1)", xlm, ylb[2])
myplot(xrg, punif(xrg, -2, 2), "X~U(-2,2)", xlm, ylb[2])

# 正态分布
xlm <- c(-10, 6) # 绘图时 X 轴范围
xrg <- seq(-10, 6, 0.01) # 绘图时变量 X 的取值
# 绘制不同正态分布的概率密度函数图像
myplot(xrg, dnorm(xrg, 0, 1), "X~N(0,1)", xlm, ylb[1])
myplot(xrg, dnorm(xrg, 0, 2), "X~N(0,2)", xlm, ylb[1])
myplot(xrg, dnorm(xrg, -3, 1), "X~N(-3,1)", xlm, ylb[1])
myplot(xrg, dnorm(xrg, -3, 2), "X~N(-3,2)", xlm, ylb[1])
# 绘制不同正态分布的概率分布函数图像
myplot(xrg, pnorm(xrg, 0, 1), "X~N(0,1)", xlm, ylb[2])
myplot(xrg, pnorm(xrg, 0, 2), "X~N(0,2)", xlm, ylb[2])
myplot(xrg, pnorm(xrg, -3, 1), "X~N(-3,1)", xlm, ylb[2])
myplot(xrg, pnorm(xrg, -3, 2), "X~N(-3,2)", xlm, ylb[2])

# 指数分布
xlm <- c(0, 10) # 绘图时 X 轴范围
xrg <- seq(0, 10, 0.01) # 绘图时变量 X 的取值
# 绘制不同指数分布的概率密度函数图像
myplot(xrg, dexp(xrg, 0.05), "X~Exp(0.05)", xlm, ylb[1])
myplot(xrg, dexp(xrg, 0.2), "X~Exp(0.2)", xlm, ylb[1])
myplot(xrg, dexp(xrg, 0.4), "X~Exp(0.4)", xlm, ylb[1])
myplot(xrg, dexp(xrg, 1), "X~Exp(1)", xlm, ylb[1])
# 绘制不同指数分布的概率分布函数图像
myplot(xrg, pexp(xrg, 0.05), "X~Exp(0.05)", xlm, ylb[2])
myplot(xrg, pexp(xrg, 0.2), "X~Exp(0.2)", xlm, ylb[2])
myplot(xrg, pexp(xrg, 0.4), "X~Exp(0.4)", xlm, ylb[2])
myplot(xrg, pexp(xrg, 1), "X~Exp(1)", xlm, ylb[2])

# 韦布尔分布
xlm <- c(0, 10) # 绘图时 X 轴范围
xrg <- seq(0, 10, 0.01) # 绘图时变量 X 的取值
# 绘制不同韦布尔分布的概率密度函数图像
myplot(xrg, dweibull(xrg, 1, 1), "X~Weib(1,1)", xlm, ylb[1])
myplot(xrg, dweibull(xrg, 1, 4), "X~Weib(1,4)", xlm, ylb[1])
myplot(xrg, dweibull(xrg, 2, 1), "X~Weib(2,1)", xlm, ylb[1])
myplot(xrg, dweibull(xrg, 2, 4), "X~Weib(2,4)", xlm, ylb[1])
# 绘制不同韦布尔分布的概率分布函数图像
myplot(xrg, pweibull(xrg, 1, 1), "X~Weib(1,1)", xlm, ylb[1])
myplot(xrg, pweibull(xrg, 1, 4), "X~Weib(1,4)", xlm, ylb[2])
myplot(xrg, pweibull(xrg, 2, 1), "X~Weib(2,1)", xlm, ylb[2])
myplot(xrg, pweibull(xrg, 2, 4), "X~Weib(2,4)", xlm, ylb[2])

# 伽马分布
xlm <- c(0, 10) # 绘图时 X 轴范围
xrg <- seq(0, 10, 0.01) # 绘图时变量 X 的取值
# 绘制不同伽马分布的概率密度函数图像
myplot(xrg, dgamma(xrg, 2, 1), "X~Γ(2,1)", xlm, ylb[1])
myplot(xrg, dgamma(xrg, 2, 2), "X~Γ(2,2)", xlm, ylb[1])
myplot(xrg, dgamma(xrg, 6, 1), "X~Γ(6,1)", xlm, ylb[1])
myplot(xrg, dgamma(xrg, 6, 2), "X~Γ(6,2)", xlm, ylb[1])
# 绘制不同伽马分布的概率分布函数图像
myplot(xrg, pgamma(xrg, 2, 1), "X~Γ(2,1)", xlm, ylb[2])
myplot(xrg, pgamma(xrg, 2, 2), "X~Γ(2,2)", xlm, ylb[2])
myplot(xrg, pgamma(xrg, 6, 1), "X~Γ(6,1)", xlm, ylb[2])
myplot(xrg, pgamma(xrg, 6, 2), "X~Γ(6,2)", xlm, ylb[2])

# F分布
xlm <- c(0, 4) # 绘图时 X 轴范围
xrg <- seq(0, 4, 0.01) # 绘图时变量 X 的取值
# 绘制不同F分布的概率密度函数图像
myplot(xrg, df(xrg, 10, 4), "X~F(10,4)", xlm, ylb[1])
myplot(xrg, df(xrg, 10, 8), "X~F(10,8)", xlm, ylb[1])
myplot(xrg, df(xrg, 4, 10), "X~F(4,10)", xlm, ylb[1])
myplot(xrg, df(xrg, 4, 20), "X~F(4,20)", xlm, ylb[1])
# 绘制不同F分布的概率分布函数图像
myplot(xrg, pf(xrg, 10, 4), "X~F(10,4)", xlm, ylb[2])
myplot(xrg, pf(xrg, 10, 8), "X~F(10,8)", xlm, ylb[2])
myplot(xrg, pf(xrg, 4, 10), "X~F(4,10)", xlm, ylb[2])
myplot(xrg, pf(xrg, 4, 20), "X~F(4,20)", xlm, ylb[2])

# 贝塔分布
xlm <- c(0, 1) # 绘图时 X 轴范围
xrg <- seq(0, 1, 0.01) # 绘图时变量 X 的取值
# 绘制不同贝塔分布的概率密度函数图像
myplot(xrg, dbeta(xrg, 1, 2), "X~Be(1,β)", xlm, ylb[1], col = "blue", ylm = c(0, 3))
par(new = TRUE)
myplot(xrg, dbeta(xrg, 1, 3), "X~Be(1,β)", xlm, ylb[1], col = "red", ylm = c(0, 3))
par(new = TRUE)
myplot(xrg, dbeta(xrg, 1, 4), "X~Be(1,β)", xlm, ylb[1], col = "green", ylm = c(0, 3))
legend("topright", pch = 1, c("β=2", "β=3", "β=4"), col = c("blue", "red", "green"))
myplot(xrg, dbeta(xrg, 5, 2), "X~Be(5,β)", xlm, ylb[1], col = "blue", ylm = c(0, 3))
par(new = TRUE)
myplot(xrg, dbeta(xrg, 5, 3), "X~Be(5,β)", xlm, ylb[1], col = "red", ylm = c(0, 3))
par(new = TRUE)
myplot(xrg, dbeta(xrg, 5, 4), "X~Be(5,β)", xlm, ylb[1], col = "green", ylm = c(0, 3))
legend("topleft", pch = 1, c("β=2", "β=3", "β=4"), col = c("blue", "red", "green"))
myplot(xrg, dbeta(xrg, 0.3, 0.5), "X~Be(α,β)", xlm, ylb[1], col = "blue", ylm = c(0, 3))
par(new = TRUE)
myplot(xrg, dbeta(xrg, 0.5, 0.7), "X~Be(α,β)", xlm, ylb[1], col = "red", ylm = c(0, 3))
par(new = TRUE)
myplot(xrg, dbeta(xrg, 0.7, 0.9), "X~Be(α,β)", xlm, ylb[1], col = "green", ylm = c(0, 3))
legend("top", pch = 1, c("α=0.3 β=0.5", "α=0.5 β=0.7", "α=0.7 β=0.9"), col = c("blue", "red", "green"))
myplot(xrg, dbeta(xrg, 2, 1), "X~Be(α,1)", xlm, ylb[1], col = "blue", ylm = c(0, 3))
par(new = TRUE)
myplot(xrg, dbeta(xrg, 3, 1), "X~Be(α,1)", xlm, ylb[1], col = "red", ylm = c(0, 3))
par(new = TRUE)
myplot(xrg, dbeta(xrg, 4, 1), "X~Be(α,1)", xlm, ylb[1], col = "green", ylm = c(0, 3))
legend("topleft", pch = 1, c("α=2", "α=3", "α=4"), col = c("blue", "red", "green"))
# 绘制不同贝塔分布的概率分布函数图像
xlm <- c(0, 2) # 绘图时 X 轴范围
xrg <- seq(0, 2, 0.01) # 绘图时变量 X 的取值
myplot(xrg, pgamma(xrg, 1, 1), "X~Be(1,1)", xlm, ylb[2])
myplot(xrg, pgamma(xrg, 1, 5), "X~Be(1,5)", xlm, ylb[2])
myplot(xrg, pgamma(xrg, 2, 1), "X~Be(2,1)", xlm, ylb[2])
myplot(xrg, pgamma(xrg, 0.5, 0.5), "X~Be(0.5,0.5)", xlm, ylb[2])

# 恢复每次输出一个图像
par(mfrow = c(1, 1))
```

## 第二题

```{r}
estimate <- function() {
    x <- runif(1, 10, 30)
    y <- runif(1, 10, 20)
    if (x > y) {
        return(y * 300)
    } else {
        return(x * 200 + y * 100)
    }
}
try <- 10000
x <- c()
for (i in 1:try) {
    x <- c(x, estimate())
}
mean(x)
```

### 第三题

```{r}
f <- function(x, y, z) {
    return(x * exp(-y^2 + z^2) + x * y * z)
}
times <- 1000
n <- 1000
data <- c()
for (i in 1:times) data <- c(data, mean(f(runif(n, 3, 6), runif(n, 2, 4), runif(n, 1, 3))))

mean(data * 2 * 2 * 3)
```

### 第四题

```{r}
layout(matrix(c(1, 3, 2, 4), ncol = 2))
times <- 1000

# Exp distribution
for (n in c(1, 2, 5, 30)) {
    expsum <- c()
    lambda <- 1 / 100
    mu <- 1 / lambda
    sigma <- 1 / (sqrt(n) * lambda)
    xdata <- seq(mu - 3 * sigma, mu + 3 * sigma, 0.01)
    estnorm <- dnorm(xdata, mu, sigma)
    for (i in 1:times) {
        expsum <- c(expsum, mean(rexp(n, lambda)))
    }
    hist(expsum, freq = FALSE, main = paste("Exponential Sample Density n=", n))
    lines(xdata, estnorm, lty = 2, col = 2, lwd = 2)
    box()
}

# Uniform distribution
for (n in c(1, 2, 5, 30)) {
    unifsum <- c()
    a <- 0
    b <- 1
    mu <- (b - a) / 2
    sigma <- (b - a) / sqrt(n * 12)
    xdata <- seq(mu - 3 * sigma, mu + 3 * sigma, 0.01)
    estnorm <- dnorm(xdata, mu, sigma)
    for (i in 1:times) {
        unifsum <- c(unifsum, mean(runif(n, a, b)))
    }
    hist(unifsum, freq = FALSE, main = paste("Uniform Sample Density n=", n))
    lines(xdata, estnorm, lty = 2, col = 2, lwd = 3)
    box()
}

# Chi-square distribution
for (n in c(1, 2, 5, 30)) {
    chisqsum <- c()
    df <- 10
    mu <- df
    sigma <- sqrt(2 * df / n)
    xdata <- seq(mu - 3 * sigma, mu + 3 * sigma, 0.01)
    estnorm <- dnorm(xdata, mu, sigma)
    for (i in 1:times) {
        chisqsum <- c(chisqsum, mean(rchisq(n, df)))
    }
    hist(chisqsum, freq = FALSE, main = paste("Chi-square Sample Density n=", n))
    lines(xdata, estnorm, lty = 2, col = 2, lwd = 3)
    box()
}

# custom distribution
# f(x)=e^x, X~U(0,1)
fx <- function(n) {
    return(exp(runif(n, 0, 1)))
}

for (n in c(1, 2, 5, 30)) {
    cstmsum <- c()
    mu <- exp(1) - 1
    sigma <- mu / sqrt(12 * n)
    xdata <- seq(mu - 3 * sigma, mu + 3 * sigma, 0.01)
    estnorm <- dnorm(xdata, mu, sigma)
    for (i in 1:times) {
        cstmsum <- c(cstmsum, mean(fx(n)))
    }
    hist(cstmsum, freq = FALSE, main = paste("fx=e^x,X~U(0,1) Sample Density n=", n))
    lines(xdata, estnorm, lty = 2, col = 2, lwd = 3)
    box()
}
```